### ISSUE TITLE
black screen lockscreen hide qs

### ISSUE THREAD

**Issue by zinhuofc** [ProjectMatrixx/packages_apps_MatrixxSettings#13]
When you activate the QS lock option on the lock screen, when you pull the bar down a little it turns black

matrix 10.3.1

https://github.com/ProjectMatrixx/android_packages_apps_MatrixxSettings/assets/131195181/331bcd7d-2dbf-4e8f-94e1-7fdaaf2472e2

[logs-2024-03-24-19-17-42[2].zip](https://github.com/ProjectMatrixx/android_packages_apps_MatrixxSettings/files/14737032/logs-2024-03-24-19-17-42.2.zip)

**Comment by mukesh22584** [comment]
Disable hide qs in lockscreen
